name: "Tarea"
description: "Tarea o pendiente de trabajo"
labels: ["chore"]
body:
  - type: textarea
    id: objetivo
    attributes:
      label: "Objetivo"
    validations:
      required: true
  - type: textarea
    id: criterios
    attributes:
      label: "Criterios de aceptación"
    validations:
      required: false
